### ISSUE TITLE
Update to latest RFCs where applicable

### ISSUE THREAD

**Issue by miqui** [OAI/sig-moonwalk#70]
OAS 3.1.0 - https://spec.openapis.org/oas/latest.html#http-status-codes mentions RFC7231 to refer to http status codes.  The new RFC 9110 obsoletes RFC7231.

https://datatracker.ietf.org/doc/html/rfc9110

Thoughts?

**Comment by miqui** [comment]
from @handrews 
>>
this is the sort of chore we'll automatically have in our pre-release checklist, as there are always new RFCs and trying to nail them down a year in advance is futile
>>

Agreed. I was thinking of doing this gradually since I did not think too many news ones would creep in and we'll have less to do. But, sure this is ok.

**Comment by handrews** [comment]
Thanks @miqui , we'll close this since we know we'll come back to it later.
