### ISSUE TITLE
Add moonwalk to list of SIGs

### ISSUE THREAD

**Issue by swaldron58** [OAI/sig-moonwalk#97]
Suggest someone update https://github.com/OAI/community/blob/main/SPECIAL_INTEREST_GROUPS.md to include moonwalk

**Comment by SensibleWood** [comment]
I've made the change - https://github.com/OAI/community/pull/14 - but need someone to head over there with the right powers to approve and merge 👍

**Comment by ralfhandl** [comment]
@lornajane @darrelmiller please help

**Comment by lornajane** [comment]
Got it! Thanks for the ping :)
